title: How about that?
author: Aleksandr Elmekeev
email: donamok@gmail.com
description: >-
  Personal blog of Aleksandr Elmekeev
baseurl: "" # the subpath of your site, e.g. /blog
domain: aelmekeev.github.io 
url: "https://aelmekeev.github.io"
github_username:  aelmekeev

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
exclude:
  .vscode
github:
  is_project_page: false
  is_user_page: true

# Github pages
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge