title: How about that?
author: Aleksandr Elmekeev
email: donamok@gmail.com
description: >-
  Personal blog of Aleksandr Elmekeev.
  <br /><br />
  Thoughts and stuff.
baseurl: "" # the subpath of your site, e.g. /blog
domain: aelmekeev.github.io 
url: "https://aelmekeev.github.io"
linkedin_url: "https://www.linkedin.com/in/aleksandr-elmekeev/"
github_username:  aelmekeev

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
exclude:
  .vscode

# Github pages
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge